import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "@/components/Providers";
import Modal from "@/components/modal";
import "./globals.css";
import 'swiper/css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FootHarmony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("relative h-full font-sans antialiased bg-gray-50", inter.className)}>
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            <Modal />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
